// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfaqeggcagogdbewczqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmYXFlZ2djYWdvZ2RiZXdjenFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDExNzgsImV4cCI6MjA2MzkxNzE3OH0.EiMlIRcFlP-cmmQo5u_XrAXry-LBBVcu1o0BuqyJCx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);